### Найти с помощью NumPy SVD для матрицы

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1,  2, 0],
              [0,  0, 5],
              [3, -4, 2],
              [1,  6, 5],
              [0,  1, 0]])

In [3]:
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s


In [4]:
print(f'{U} \n')
print(f'{D} \n')
print(V.T)

[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]] 

[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]] 

[[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]


In [5]:
# проверка
print(np.dot(np.dot(U, D), V.T))
print(f'\n {A}')

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]

 [[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


### Для матрицы из предыдущего задания найти:

а) евклидову норму;

б) норму Фробениуса.

In [11]:
n = 0
for i in D:
    for j in i:
        n = n + (j**2)
        print(n)
print(n)
np.sqrt(n)            

77.87831030477996
77.87831030477996
77.87831030477996
77.87831030477996
115.58535330548408
115.58535330548408
115.58535330548408
115.58535330548408
122.00000000000007
122.00000000000007
122.00000000000007
122.00000000000007
122.00000000000007
122.00000000000007
122.00000000000007
122.00000000000007


11.045361017187265

In [8]:
np.linalg.norm(D)

11.045361017187265

In [12]:
D

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [16]:
A = 8.82**2

In [17]:
B = 6.14**2

In [18]:
C = 2.53**2

In [21]:
R = A + B + C

In [22]:
np.sqrt(R)

11.04051176350082

In [ ]:
np.linalg.norm(A)