### 1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4

In [ ]:
а) невозможно выполнить
б) 2х3
в) 8x8
г) 4х4

In [1]:
import numpy as np
#a
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(np.dot(a, b), np.dot(a, b).shape)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [2]:
#б
a = np.array([[1, 2, 3, 4, 5], [3, 4, 5, 6, 7]])
b = np.array([[1, 2, 3], [3, 4, 4], [5, 6, 5], [7, 8, 6], [7, 8, 7]])
print(np.dot(a, b), np.dot(a, b).shape)

[[ 85 100  85]
 [131 156 135]] (2, 3)


In [3]:
#в
a = np.array([[1, 2, 3], [3, 4, 5], [1, 2, 3], [3, 4, 5], [1, 2, 3], [1, 2, 3], [3, 4, 5], [1, 2, 3]])
b = np.array([[1, 2, 3, 2, 3, 2, 3, 1], [1, 2, 3, 2, 3, 2, 3, 1], [1, 2, 3, 2, 3, 2, 3, 1]])
print(np.dot(a, b), np.dot(a, b).shape)

[[ 6 12 18 12 18 12 18  6]
 [12 24 36 24 36 24 36 12]
 [ 6 12 18 12 18 12 18  6]
 [12 24 36 24 36 24 36 12]
 [ 6 12 18 12 18 12 18  6]
 [ 6 12 18 12 18 12 18  6]
 [12 24 36 24 36 24 36 12]
 [ 6 12 18 12 18 12 18  6]] (8, 8)


In [4]:
#г
a = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [1, 2, 3, 4], [3, 4, 5, 6]])
b = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [1, 2, 3, 4], [3, 4, 5, 6]])
print(np.dot(a, b), np.dot(a, b).shape)

[[22 32 42 52]
 [38 56 74 92]
 [22 32 42 52]
 [38 56 74 92]] (4, 4)


### 2. Найти сумму и произведение матриц  A=([[1, -2], [3, 0]])  и  B=([[4, -1], [0, 5]])

In [5]:
A = np.array([[1, -2],
              [3, 0]])

B = np.array([[4, -1],
              [0, 5]])

In [ ]:
A + B = ([[5, -3],
          [3, 5]])

A * B = ([[4, -11],
          [12, -3]])

In [6]:
print(A + B)
print(np.dot(A, B))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


### Вычислить линейную комбинацию  3A−2B+4C  для матриц A=([[1, 7], [3, -6]]),  B=([[0, 5], [2, -1]]),  C=([[2, -4], [1, 1]])

In [7]:
A = np.array([[1, 7],
              [3, -6]])

B = np.array([[0, 5],
              [2, -1]])

C = np.array([[2, -4],
              [1, 1]])

In [ ]:
3A - 2B + 4C = [
                [11,  -5],
                [ 9, -12],
]

In [8]:
print(3*A - 2*B + 4*C)

[[ 11  -5]
 [  9 -12]]


### Дана матрица  A=([[4, 1], [5, -2], [2, 3]]) Вычислить  A A.T  и  A.T A

In [9]:
A = np.array([
              [4,  1],
              [5, -2],
              [2,  3]
])

In [ ]:
A * A.T = [[4,  1], * [[4,  5, 2]  =  [[17, 18, 11]
           [5, -2],    [1, -2, 3]]     [18, 29,  4]
           [2,  3]]                    [11,  4, 13]]

In [ ]:
A.T * A = [[4,  5, 2]  * [[4,  1],  = [[45,  0]
           [1, -2, 3]]    [5, -2],     [ 0, 14]]
                          [2,  3]] 

In [10]:
print(np.dot(A, A.T))

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [11]:
print(np.dot(A.T, A))

[[45  0]
 [ 0 14]]


### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [12]:
def check_matrix(matrix_a, matrix_b):
    if len(matrix_a[0]) == len(matrix_b):
        return True
    else:
        print('Неподходящий размер матриц')
        return False

In [13]:
def multi_matrix(matrix_a, matrix_b):
    if check_matrix(A,B):
        new_matrix = []
        for i in range(len(A)):
            matrix_list = []
            for k in range(len(B[i])):
                subtotal = 0
                for j in range(len(A[i])):
                    subtotal = subtotal + A[i][j]*B[j][k]
                matrix_list.append(subtotal)
            new_matrix.append(matrix_list)
        return new_matrix

In [14]:
A = [[5, 2, 3, 4],
     [2, 4, 6, 1]
    ]

B = [[5, 2],
     [2, 4],
     [1, 2]
    ]
multi_matrix(A, B)

Неподходящий размер матриц


In [15]:
A = [[5, 2, 3],
     [2, 4, 6]
    ]

B = [[5, 2],
     [2, 4],
     [1, 2]
    ]
multi_matrix(A, B)

[[32, 24], [24, 32]]

### 1. Вычислить определитель

In [ ]:
A = [
    [sin x, -cos x]
    [cos x,  sin x]
]

In [ ]:
det (A) = sin x * sin x - cos x * -cos x = sin^2 x + cos^2 x = 1 

In [16]:
B = np.array([
    [4, 2, 3],
    [0, 5, 1],
    [0, 0, 9]
])

In [ ]:
det(B) = 4 * 5 * 9 = 180

In [17]:
C = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
det (C) = 1 * (5*9 - 6*8) - 2 * (4*9 - 6*7) + 3 * (4*8 - 7*5) = -3 + 12 - 9 = 0

In [18]:
A = np.array([
    [np.sin(1), -np.cos(1)],
    [np.cos(1),  np.sin(1)]
])
print(f'определитель A = {np.linalg.det(A):.0f}')
print(f'определитель B = {np.linalg.det(B):.0f}')
print(f'определитель C = {np.linalg.det(C):.0f}')

определитель A = 1
определитель B = 180
определитель C = 0


### 2. Определитель матрицы  A  равен  4 . Найти:

а)  det(A**2) 

б)  det(A.T) 

в)  det(2*A) 

In [ ]:
для треугольной матрицы:
a) det(A**2) = 4**2 = 16
б) det(A.T) = 4
в) det(2A) = 4*(кол-во строк/столбцов в матрице) = 4*2*2*2 = 32 (для 3х3), 4*2*2*2*2 = 64 для 4х4 и тд

In [19]:
A = np.array([
    [1, 2, 3, 1],
    [0, 2, 6, 1],
    [0, 0, 2, 1],
    [0, 0, 0, 1]
])

print(f'определитель A**2 = {np.linalg.det(A**2):.0f}')
print(f'определитель A.T = {np.linalg.det(A.T):.0f}')
print(f'определитель A*2 = {np.linalg.det(A*2):.0f} \n')

B = np.array([
    [1, 2, 3],
    [0, 2, 6],
    [0, 0, 2],
])

print(f'определитель B**2 = {np.linalg.det(B**2):.0f}')
print(f'определитель B.T = {np.linalg.det(B.T):.0f}')
print(f'определитель B*2 = {np.linalg.det(B*2):.0f}')

определитель A**2 = 16
определитель A.T = 4
определитель A*2 = 64 

определитель B**2 = 16
определитель B.T = 4
определитель B*2 = 32


### 3. Доказать, что матрица вырожденная

In [20]:
A = np.array([
    [-2,   7, -3],
    [ 4, -14,  6],
    [-3,   7, 13]
])

In [ ]:
прибавим 2 строку к 3:
    
   [[-2,   7, -3],
    [ 4, -14,  6],
    [ 1,  -7, 19]]

прибавим удвоенную 1 строку ко 2:
    
   [[-2,   7, -3],
    [ 0,   0,  0],
    [ 1,  -7, 19]]

прибавим 1 строку к 3:
    
   [[-2,   7, -3],
    [ 0,   0,  0],
    [-1,   0, 16]]

вычтем 3 строку из 1:
    
   [[-1,   7,-19],
    [ 0,   0,  0],
    [-1,   0, 16]]

вычтем 1 строку из 3:
    
   [[-1,   7,-19],
    [ 0,   0,  0],
    [ 0,   0, 16]]

поменяем местами 2 и 3 строку:
    
   [[-1,   7,-19],
  - [ 0,   0, 16],
    [ 0,   0,  0]]

определитель равен -(-1*0*0) = 0, матрица вырожденная 

In [21]:
print(f'определитель A = {np.linalg.det(A):.0f}')

определитель A = 0


### 4. Найти ранг матрицы:

In [22]:
A = np.array([
    [1, 2, 3],
    [1, 1, 1],
    [2, 3, 4]
])

B = np.array([
    [0, 0, 2, 1],
    [0, 0, 2, 2],
    [0, 0, 4, 3],
    [2, 3, 5, 6]
])

In [ ]:
A
   [[1, 2, 3],
    [1, 1, 1],
    [2, 3, 4]]

вычтем из 3 строки 1:
   
   [[1, 2, 3],
    [1, 1, 1],
    [1, 1, 1]]
    
вычтем из 1 и 3 строк 2 строку:
    
   [[0, 1, 2],
    [1, 1, 1],
    [0, 0, 0]]

переставим 1 и 2 строку:
    
   [[1, 1, 1],
  - [0, 1, 2],
    [0, 0, 0]]

ранг матрицы А = 2

In [23]:
print(f'Ранг матрицы А = {np.linalg.matrix_rank(A)}')

Ранг матрицы А = 2


In [ ]:
B
   [[0, 0, 2, 1],
    [0, 0, 2, 2],
    [0, 0, 4, 3],
    [2, 3, 5, 6]]
    
отбросим 3 строку, т.к она является суммой 1 и 2:

   [[0, 0, 2, 1],
    [0, 0, 2, 2],
    [2, 3, 5, 6]]
    
вычтем 1 строку из 2 и переставим их:

   [[0, 0, 0, 1],
  - [0, 0, 2, 1],
    [2, 3, 5, 6]]

ранг матрицы B = 3

In [24]:
print(f'Ранг матрицы B = {np.linalg.matrix_rank(B)}')

Ранг матрицы B = 3
